package com.devwarex.kabeertask.models

data class Employee(
    val EMP_ID: Int,
    val CUSTOM_ID: Int,
    val EMP_DATA_AR: String,
    val EMP_DATA_EN: String,
    val JOBCODE: Float,
    val JOBNAME_AR: String,
    val JOBNAME_EN: String,
    val SEC_NAME_AR: String,
    val SEC_NAME_EN: String,
    val CONTRACTSTDATE: String,
    val ATM_ACCOUNT: String?,
    val MAR_STATUS_EN: String?,
    val MAR_STATUS_AR: String?,
    val EMP_GENDUR: String,
    val SAL_COMP_CODE_A: Float,
    val COMP_DESC_A_AR: String,
    val COMP_DESC_A_EN: String,
    val SAL_VALUE_A: String,
    val SAL_COMP_CODE_D: String,
    val COMP_DESC_D_AR: String,
    val COMP_DESC_D_EN: String,
    val SAL_VALUE_D: String,
    val SAL_VALUE_NET: Float,
    val CURRSYMBOL_AR: String,
    val CURRSYMBOL_EN: String,
    val FRACTIONNAME_EN: String,
    val FRACTIONNAME_AR: String,
    val STATUSNAME_AR: String,
    val STATUSNAME_EN: String,
    val STATUS_AR: String,
    val STATUS_EN: String,
    val EMP_PIC: String?
)
